### ISSUE TITLE
Repurpose "Bootcamp Launch Checklist" to "Instructor Reminders" in Dashboard

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1189]
Currently the Bootcamp Dashboard Checklist is a static list of things instructors need to do in order to prepare their Bootcamp for Launch. What if we turn this into a dynamic "Reminder" checklist, wherre it includes other things like:

- Students who need attention or have un-replied messages
- Iterative revisions to their Action Plan content (Principle of Iteration)
- Anything else that the instructor needs to pay attention to for each Bootcamp

Note that this is also related to #1347

TODO

- [ ] Rename "Bootcamp Launch Checklist" to "Instructor Reminders" in Dashboard
- [ ] Add other types of reminders to that section such as un-replied student messages
- [ ] Wire in MenchBot reminders to the addition of a new checklist Item to notify
