### ISSUE TITLE
QA 2.0 & Fix PHP Errors

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1287]
#Now that #445 is in place, let's monitor these errors and have them fixed

- [x] Rename "Completion Prizes" with "Completion Awards" #1267
- [x] Iterate MenchBot Leaderboard/Action Plan logic #1051
- [x] Change "Leaderboard" to "Classmates" #1293
- [x] Remove Points from Terminology Index #1239
- [x] Send task completion emails ONLY for tasks that have notes in them #1219
- [x] Fix Technical Issue of Showing the Student Progress Card for Older Classes #1154
- [x] Student admission in multi Bootcamps, and various testing cases
- [x] audit all remix_admissions() calls
- [x] audit all remix_bootcamps() calls
