### ISSUE TITLE
List of all student engagement strategies

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#1351]
@shervine Goal: to list all the strategies/features Mench uses and will use to ensure students stay engaged and are more likely to complete classes all the way to the end. This strategies only apply to after a class has started.

## Automated Reminders/Notifications

- [x] Group call reminders to Students 1 hour before
- [x] Group call reminders to Students 10 Minutes before
- [x] Group call reminders to Instructor 2 Hours before
- [x] Group call reminders to Instructor 10 Minutes before
- [x] New milestone notification to students
- [x] New milestone notification to instructor
- [x] Task Completion Reminder: Less than 1% after 10%
- [x] Task Completion Reminder: Less than 10% after 25%
- [x] Task Completion Reminder: Less than 25% after 50%
- [x] Task Completion Reminder: Less than 50% after 75%
- [x] Task Completion Reminder: Less than 100% after 90%
- [ ] Classmate has completed milestone
- [ ] Classmate has completed class
- [ ] Student is on the top 20%
- [ ] Student is top of the class
- [ ] Student has posted question to class
- [ ] Student has replied to your question
- [ ] A new task has been added to the class
- [ ] A task has been removed from the class
- [ ] Daily/Weekly Student Briefings (#1101)
- [ ] Student to give daily/weekly progress update reminder(via audio/video message)

## Automated Drip Messages
- [ ] Automated questions: ie: How is everything going {first_name}?
- [ ] Educational drip messages: ie: teaching how the platform works

## Manual Drip Messages
- [x] Tip drip messages (class related)
- [ ] Motivational drip messages
- [ ] Inspirational drip messages
- [ ] Question drip messages

## Hint messages
- [ ] Task hint messages: available on demand

## Announcements
- [ ] Broadcast announcements by Mench (upcoming events, upgrades, changes, wins)
- [ ] Weekly content update by Mench
- [ ] Broadcast announcements by instructors

## Task Planning
- [ ] The first task of every week should ask students to schedule on the Calendar enough time to complete the estimated task time. Ie: if the total estimated task time is 8 hours for the week they should submit a screenshot of 8 hours allocated in their week to do those tasks.

## Social Strategies
- [ ] Display faces of all classmates in action plan
- [ ] Push message with all classmate faces carrousel at the beginning of class
- [ ] Create task that asks students to record a <60sec intro video of themselves
- [ ] Allow students to message each other
- [x] Weekly group calls where students can interact with each other
- [ ] Accountability partners
- [ ] Group tasks and projects
- [ ] Local meetups
- [ ] Instructors to actively make introductions among students 
- [x] Student progress leaderboard
- [ ] Pain from disconnect: ie: remind what student will lose if they quit (points, rewards, content)
- [ ] Member spotlights - showcase members
- [ ] Announce Birthdays and anniversaries

## Reward Strategies
- [ ] Give students surprise digital bonuses/gifts (new content, tickets, discounts, coupons)
- [ ] Send students physical gifts (merchandise, t-shirts, mugs, books, medals, cards)
- [ ] Certificates of achievement

## Exit Strategies
Relates to things to do after a student has taken a class
- [ ] Create a task for students to submit feedback via a Google Form
- [ ] Create a task for students to record a short video of themselves providing feedback ([watch a great example from Jason Cannon](https://www.youtube.com/watch?v=yv9rgLGsYfA))
