### ISSUE TITLE
Brainstorm Growth Hacking tools for Instructors

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#1436]
@shervine We really need to focus on increasing our delta and have to put our growth hacking hats on and come up with one or [two simple tools](https://videofruit.com/products/) that could spread virally and get us tons of leads.

These tools would be built by contractors. I preselected a few potential candidates on Upwork using [this search](https://www.upwork.com/ab/profiles/search/?q=chrome%20extension&revenue=1000&nss=90&rate=10-30&pt=independent&hrs=100&rhrs=yes&last=60&page=2).

Let's use this issue to list a few potential candidates:

- [ ] Personal Delta Reporting tool (#1474): As soon as they enter their email address and user profile we give send them to a nice page showing them their engagement rate and how it compares to udemy's average. Based on the value we can tell them they are on the top 10% or bottom 10% and give them improvement tips if they are sucking. We can send them the report once a month.
- [ ] Competitor's Delta Reporting tool (#1474): Same as above but we allow them to enter up to 5 competitors so they can compare themselves to them (We can charge them $1 for each extra instructor they want to track)
- [ ] Student Growth reporting tool (#1475): a similar tools was used by VideoFruit to grow their email list to over 40K subscribers. The instructor enters what is their student count goal over the next 12 months and every time they open a new tab of Chrome we tell them how many new students they got and whether they are on track to meet this goal or not. It's a genius idea to keep instructors focus on growth. Based on [ListGoal Chrome Extension by VideoFruit](https://chrome.google.com/webstore/detail/list-goal/lbeomnhfagdagoldnknhbfjfkdndfjof)
- [ ] Course Hosting Platform Picker (#1476): tool to help instructors decide where to host their courses (Udemy/SkillShare/Teachable/Thinkific/Kajabi/Wordpress) - Based on [VideoFruit's Email Service Picker](https://whatemailserviceshouldiuse.com/)
- [ ] Funnel Building Metrics Extension (#1477): this tool is based on the YouTube funnel metrics calculator I created. The Idea is instructors enter a revenue goal and we tell them how many views they need to get in order to meet that revenue goal. Instead of views we could use email subscribers or webpage views. We could calculate how well they are doing using industry average conversion rates on similar funnels or let them input their own conversion rates themselves.
