### ISSUE TITLE
Choose Target Segment of Instructors for Focused Sales

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1487]
@grumo Just sent you a voice note about this. The idea is that as a platform, we should continue focusing on our supply-side funnels and have them to build learning programs with us. This issue outlines

We should choose between them once we have more clarity on #1493 :

## Choose Target

- [x] Blockchain experts #1397 #1417 #1471 
- [x] Job Placement Consultants #1123 
- [x] Javascript experts #1378 
- [x] Python experts
- [x] Machine Learning
- [ ] Udemy Instructors (Done with 1100 Targets)
- [ ] Personality test consultants #1461 #1485 #1469
- [ ] Educational Institutes #1284 
- [ ] Sales rep training consultants #1376
- [ ] Physical coding Bootcamps #1299 
- [ ] Professional Readers (Like [Maria Popova](https://tim.blog/2014/10/21/brain-pickings/)) #1451 - The idea here is to understand how these readers organize their notes and try building a tool for that as part of our #1433  
- [ ] Influencers: Approach people with huge audiences ([list of influencers in CRM](https://app.hubspot.com/sales/3944789/contacts/list/view/1084083/?))
