### ISSUE TITLE
Mench Branding V2

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1494]
## Considerable Things To do

- [ ] Change Mench Logo to simple M via 99design contest
- [ ] Change theme to Blue like messenger which also impacts #1491 
- [ ] Change typography to make it more simple, I like [HotJar](https://www.hotjar.com/)
- [ ] Change email templates (maybe?)
- [ ] Work within the frames of the console and redesign colors/UI but keep same structure
- [ ] Super Simple & Instructor-Focused Mench Home Page Design #1260
- [ ] Public Pricing Page for Instructors #1221
- [ ] Integrations Page to explain everything Mench is connected to #633  
- [ ] Rename Launch to Features page and focus on #1493
- [ ] Ideas here...

To be discussed further

## Design inspirations

- https://slack.com
- https://stripe.com
- http://rasa.com/
- https://www.datacamp.com/courses/building-chatbots-in-python
- https://www.hotjar.com
- https://manychat.com/
- https://www.useloom.com/
