### ISSUE TITLE
Fixed Instant/Free Milestone in Action Plan

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1499]
So we can enable instructors to give a glimpse of their course for free and instantly to their students.

- [ ] Add a fixed Milestone in Action Plan called "Free/Instant Milestone" which does not have the day or week assigned to it. Instead, it's content sent to the student when they signup. They can also complete the tasks and get a sense for what is about to happen before paying
- [ ] Make signup easier in Landing Page to get into Messenger or Web based Action Plan #1491 
- [ ] See https://www.datacamp.com/courses/building-chatbots-in-python for design ideas
- [ ] Enable students to signup and access all input/output Tasks #1272
