### ISSUE TITLE
Top Recommended Features for Mench 2nd Gen

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#1622]
#@shervine I'm using this issue to list the features I think we should implement:

- [x] Show counters on main page for: Total Bootcamps | Total Students | Completion Rate #1651 
- [x] Create Instructor profile pages listing their stats and all their available bootcamps #1541
- [ ] Create student profile pages listing their stats and all the bootcamps they graduated from
- [x] Add search functionality to find bootcamps/instructors/students #1652
- [x] Enable instructor quick registration via Facebook Login/Google/Github Login #1222
- [x] Group bootcamps into categories (PHP, Python, Javascript, React, Wordpress, Interview prep) #1651
- [x] Create review system #1148 #1382
- [x] Display reviews on bootcamp landing pages #1148
- [ ] Create dashboard for students to track all their bootcamps - **This is already done in a basic level via their Bootcamp management URL sent to them. We need more advance functions once we have many students with multiple Bootcamps**
- [x] Recommend other bootcamps on bootcamp landing pages #1148
- [x] Add a couple default drip messages to all bootcamps to collect feedback from students : **This is already in place with the automated reminders (i.e. less than 70% complete after 90% of Class)**
  - ie: For paid bootcamps: {first_name}, how is everything going? | {first_name}, Let me know if you need help. Cheers
  - ie: For free bootcamps: Hey {first_name}, quick question, what do you think of Mench so far? | Hey {first_name}, is Mench working well for you? | Hey {first_name}, just curious, how did you find about Mench?
- [x] Implement commenting system to store previous questions and answers #1419
- [ ] Redirect new students to landing page to encourage them to buy more courses
- [ ] Add CTA's on all Zendesk docs
- [ ] Create 52 week calendar to show students what bootcamps they've purchased and all the available weeks they have to learn new things by buying new bootcamps 
- [ ] Add automated daily report question message: What did you do today?
- [ ] Implement proof-of-work technology to proof tasks are completed by authentic user
- [ ] Implement peer review system. 2 or more classmates need to approve a submission before it's valid
