### ISSUE TITLE
Study paragonone.com & themuse.com

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#1799]
Get inspired from paragonone.com and tweak platform based on learnings.

https://www.paragonone.com https://www.crunchbase.com/organization/paragon-one (2M Funding)
https://www.themuse.com https://www.crunchbase.com/organization/the-muse (28M Funding)

## Trello Board

https://trello.com/b/uiB8K6q3/paragon-one-the-muse

## TODO

- [x] Rename instructors to coaches?!
- [x] Rename mentorship to coaching
- [ ] Separate list of instructors on website
- [ ] Move coaching price to instructor profile
- [ ] Assign Bootcamps based on shared Topics (see [trello board](https://trello.com/b/uiB8K6q3/paragon-one-the-muse)), not a single lead instructor
- [ ] On checkout enable students to add chat-line + 1-on-1 coaching
- [ ] #1664 with inspiration from https://www.paragonone.com/#pricing
- [ ] Introduced Q&A to match to advisors, somewhat similar to #1798 but for people
- [ ] Create student assessment like https://app.paragonone.com/assessment/questions with the ability to skip a question like themuse.com
