### ISSUE TITLE
Conversational Engine V1.1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2035]
Improvements to the conversation engine V1 which was released last week! The goal is to make the conversation feel very smooth and functional so we can build trust with users early on.

Deprecate/update the following entity integrations in the code base:

- [x] Update actionplan_next_step() so it works with en_id
- [x] Remove actionplan_ln_id
- [x] en_ids_6138 & en_all_6138
- [x] @ 4235 Intention Set
- [x] @ 4559 Step Completed

TODO

- [x] Implement double column removal from title
- [x] Implement facebook attachment ID & test
- [x] List featured intents if REF variable not passed
- [x] test in_next_actionplan()
- [x] Enable trainers to create conditional children in UI with new tab
- [x] Limit OR Branch Answer to 1 Intent Only: Currently users can select multiple answers by navigating and choosing. Let's limit this to a single answer, so if users change their answer we would SKIP the previous answer and complete the new answer.
- [x] Auto Move to Next if Nothing to be done upon OR Answer
- [x] Add SKIP confirmation to ensure student knowns what they are doing
- [x] Allow to chat with students in Messenger #2041
- [x] Fix bug for AND tree after an OR tree: https://mench.com/intents/7662
- [x] Fix facebook webhook engagement login bug
- [x] Implement Intent Trigger Statements #1981 as users are searching for some intents that they cannot find as the system needs more synonyms for our popular intents
- [x] Give users a single path in AND branches (Currently they can choose any branch)
- [x] Test and fix bugs with flat tree subscriptions (1 level deep OR branch for example) [We get error: "Unable to locate OR selection for this subscription"]
- [x] Fix bug that enables users to subscribe to orphan branches (which causes an error)
- [x] Auto Move to Next if Nothing to be done upon OR Answer #2023
- [x] Test Miguel JS Exam Bug Answer not moving

Conversational Engine V1.2 update ideas:

- [x] Implement Intent Response Requirements
- [x] Handle Duplicate Sub-trees #2009
- [x] Enable the student to provide written response and URL responses directly via Messenger. The workflow would ask users to type in their answer, and whatever they enter would be nominated as the answer where they can confirm via a quick reply. This is currently only possible through the browser Action Plan. Capture student multi-media answers right from Messenger such as Text, Audio, Video, Images #2069
- [x] Give users option to set their notification setting #2032
- [x] Expand language formats for popular statements so the bot feels more natural while making "glue statements"
