### ISSUE TITLE
Cron to Share Assessment Results

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2077]
A PDF which would be issued to students who complete certain trees (Like JS, jQUery, NodeJS, etc...) which would give contextual information on the assessment taken, its authors/references and the variance of questions asked so the reader of the Certificate of Technical Assessment can better understand the qualifications of the user.

## On-demand assessment

With the previous version of Mench students where able to take an assessment but they did not get to see their results as it was not yet implemented.

This feature uses the Intent Message Webhooks to make an external call on specific intent trees to process student's assessment and give them two score:

- % Score from 0-100
- Relative percentile position compared to other students who have taken the same assessment. This should be a cron job in case there is not enough participants (min 20 maybe?)

## TODO

To enable percentage style and relative comparison of student answers to OR branches.

- [x] Implement c_points as a new intent filed
- [ ] Think about the overall design of the point system and what c_points means for calculations. i.e. are the values of parent/child multiplied by each other, or simply added-up?
- [ ] Add points link box to echo_c() that will load all child intents ordered by points with a way to quickly edit those points. This view gives a points-driven view on the tree so the trainer can optimize the overall points relative to each other, which is how the final % score is calculated.
- [ ] Calculate absolute percentage per tree (each branch has its own) when students submit intents that result in the completion of a tree
- [ ] Cron job to calculate relative percentile based on other responses and inform students about those scores... It should happen within a minute if there are 20+ response submissions. If not, student would receive it when the tree hits that many responses.

Related to #2067 & #2068

**Comment by shervine** [comment]
No longer needed as we retired webhooks and assessments in favour of #2080
