### ISSUE TITLE
Consider Mining Adjective Check List Personality Assessment

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2445]
Inspired by #2444 The [Adjective Check List (ACL)](https://en.wikipedia.org/wiki/Adjective_Check_List) is a psychological assessment containing 300 adjectives used to identify common psychological traits.[1] The ACL was constructed by Harrison G. Gough and Alfred B. Heilbrun, Jr. with the goal to assess psychological traits of an individual.[2] The ACL measures 37 scales within 5 categories: modus operandi (4 scales), need (15 scales), topical (9 scales), transactional analysis (5 scales), and origence-intellectence (4 scales).[3] To complete the ACL, respondents select the adjectives that they believe describe themselves (or someone else). Any number of items may be selected from the list of adjectives. In this way, the results are customized to include only those adjectives salient to the individual being assessed. The ACL takes between 10-15 minutes to complete and may be administered to individuals, groups, or used by researchers to describe study participants.[3] The ACL is protected by copyright law, published by Consulting Psychologists Press, and distributed by Mind Garden, Inc.

## 300 Adjectives

https://docs.google.com/spreadsheets/d/18Ep7uhZ7nKBNd8lVwGAmfm0JM6msurs5zkDDoarA15E

## Mapped to 20 Scales

https://docs.google.com/spreadsheets/d/18Ep7uhZ7nKBNd8lVwGAmfm0JM6msurs5zkDDoarA15E/edit#gid=758859207

## TODO

- [ ] Read https://en.wikipedia.org/wiki/Adjective_Check_List
- [ ] Read https://pairin.com/our-science-faq/
- [ ] Group adjectives based on the 20 scales
- [ ] Assess users based on 4 levels on each scale based on the adjectives they choose

**Comment by grumo** [comment]
@shervine to replicate the assessment we would need the response->scale correlation keys. We could guess the correlation but it would be less accurate.

**Comment by shervine** [comment]
I don't think this is really relevant at this time.
