### ISSUE TITLE
Expand scope of Intent Types

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#2526]
Similar to Typeform, we want to give miners the option to ask for:

- [ ] Number
- [ ] Dates
- [ ] Address
- [ ] Call to Action: Allows to enter a URL which the user can open inside messenger/iframe
- [ ] Times Answer #2293 
- [ ] Locked Intents #2483 
- [ ] OR Multiple Answers Intent Type V1 #2410
- [ ] Enable 10+ OR Intent Answers via Messenger #2411
- [ ] Random Path V1 #2311
- [ ] Automate Candidate Background Checks #2541
- [x] Stop Intention V1 #2587

These allow for more types of conversation creation that will support more workflows.
