### ISSUE TITLE
Introduce Break Milestones

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#399]
- [ ] Search for week and replace
- [ ] Test landing page
- [ ] Implement Break Windows for both week and days

Also related to #398
