### ISSUE TITLE
Break Milestones V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#577]
- [x] Checkmark in Milestone details tab
- [x] different UI in Landing page
- [x] Different UI in Action Plan + student side
- [x] Check to make sure no child-tasks
