### ISSUE TITLE
Milestone Message Simulator V1

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#726]
Help instructors understand what happens to their students more explicitly.

- [x] Require them to Activate MenchBot
- [ ] Implement Quick Reply logic in tree_message()
- [ ] Add button to send sample messages
