### ISSUE TITLE
Launch Page V2.0

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#841]
Improvements to how we communicate our value proposition to our target instructors via:

https://mench.co/launch

## TODO
- [ ] Show iPhone X Frame to emphasize Mench is an educational messaging platform
- [ ] Make more targetted towards Udemy instructors
- [ ] Pitch "Micro Challenges/Bootcamps" that could be Free (in which case you don't pay)
- [ ] Ideal for all Udemy courses to make them more pro-active
- [ ] Only pay if you run a paid bootcamp
- [ ] Focus more on Micro-Bootcamps as opposed to Bootcamps
- [ ] Make page more visually appealing
