### ISSUE TITLE
V1.5 Feature requests

### ISSUE THREAD

**Issue by grumo** [askmench/mench-web-app#882]
@shervine I had a call with [Alvin Phang](https://app.hubspot.com/sales/3944789/deal/239246091/?interaction=note). He had many great questions and suggestions (Call recording: https://www.youtube.com/watch?v=ZQ2Z0rxe718)
- [ ] Message X out of N counter indicator so students know how many messages in total will be delivered and don't forget to click next and miss any messages
- [x] Change Weekly Office Hours to Weekly Live Group Calls
- [x] Enable setting to allow students to pay first and then ask them questions (Alving says this converts better) - **We talked about this, all payments will be first anyways**
- [x]  Make countdown timer under "Reserve Your Seat" button a lot bigger (about the same width as the button itself <- I've heard this feedback from 2 instructors already)
- [ ] Add social media sharing buttons to the landing page
- [ ] Enable free 7-day trial
- [x] Enable payment plans - Merged with https://github.com/menchco/mench-finance/issues/6
- [x] Make bootcamp title clickable so it's easier to navigate to the landing page (@shervine could you make it to open on a new tab? thx)
- [x] Prompt students via message to work on next task as soon as previous task is completed (Neil Anderson) - Merged with #923
- [x] Let instructors select cart closing date. ie: if class starts on Monday, close registrations on Friday (Neil Anderson) Merged with #924

@shervine [Mikey Borup](https://app.hubspot.com/sales/3944789/deal/239249528/?interaction=note) had tons of feedback. Call is worth listening too as he asked a ton of questions -> https://youtube.com/watch?v=EY7J6_bL6Xk

Main points (from the call and from Messenger):

- [ ] Allow students to click a button "Open in website" from the Messenger Action Plan
- [x] Convert Vimeo/YouTube/Wistia video links to embedded videos inside the Action Plan web view <- [ ] LOVE THIS - Merged with #891
- [ ] Ability to join your own bootcamp or a way to see how the students experience messages - Since we're forcing all instructors to join the Bootcamp Launching Bootcamp, they get to experience this over there...
- [ ] Ability to edit the content of autoresponder messages
- [x] After a task messages are delivered include a message with a link that opens directly that task inside the Action Plan web view - Merged wit #923
- [x] Enable discount coupons to offer as bootcamp completion rewards so existing students pay less for joining more bootcamps - Merged with #512
- [x] Ability to reject a task submission in case the student didn't do a good job - Merged with #925
- [ ] Ability to add testimonials manually to the landing page - Will be done automatically once we have the review system in place.
- [ ] Allow instructors to edit how many points are awarded for a task so they can be also based on complexity not just on duration. Because watching a 4 hour video is not as hard as working on a problem for 4 hours.
