### ISSUE TITLE
Automate Milestone Dispatch Messages

### ISSUE THREAD

**Issue by shervine** [askmench/mench-web-app#935]
- [x] Messages to be communicated automatically when Class Starts
- [x] Ensure messages are being logged properly here
- [x] Give separate fields for URL, comments & maybe feedback
- [x] After a task messages are delivered include a message with a link that opens directly that task inside the Action Plan web view
- [x] Give students more context on how to complete a Task by referencing its Task Completion settings
- [x] Implement submission requirements notes: requires a URL + Completion Notes
- [ ] Daily Status Update
- [x] Milestone Kickstart Notifications
